<div class="selectionBox">
    <form action="" method="post">
        <p class="headerSelectionBox">Etes-vous sûr de vouloir supprimer ce support ?</p>
        <table class="searchContainer">
            <tr><th>Classe :</th><td><?php echo $parms['nom_classe']; ?></td></tr>
            <tr><th>Matière :</th><td><?php echo $parms['nom_matiere']; ?></td></tr>
            <tr><th>Titre :</th><td><?php echo $parms['titre']; ?></td></tr>
            <tr><th>Fichier :</th><td><?php echo $parms['nom_fichier']; ?></td></tr>
        </table>
        <p class="submitContainer">
            <input name="validation" type="submit" value="Supprimer" />
            <input name="annulation" type="submit" value="Annuler" />
        </p>
    </form>
</div>
