<?php
echo('
	<div class="selectionBox">
		<form action="" method="post">');
if ($_SESSION['user']['privileges'] == 'eleve') {
	echo('
			<p class="headerSelectionBox">Veuillez préciser votre recherche.</p>
			<table class="searchContainer">
				<tr>
					<th>Mots clés :</th>
					<td>
						<input name="mots_cles" type="text" value="' . $parms['mots_cles']. '" />
						<input ' . ($parms['and'] ? 'checked="checked" ' : '') . 'name="and" type="checkbox" />Tous les mots
					</td>
				</tr>
				<tr>
					<th>Matière :</th>
					<td>
						<select name="id_matiere">
							<option value="-1">Toutes</option>');
	foreach ($parms['matieres'] as $m) {
		echo('<option ' . ($m['id_matiere'] == $parms['id_matiere'] ? 'selected="selected" ' : '') . 'value="' . $m['id_matiere'] . '">' . $m['nom_matiere'] . '</option>');
	}
	echo('
						</select>
					</td>
				</tr>
				<tr>
					<th>Rechercher dans :</th>
					<td>
						<input ' . ($parms['titre_on'] ? 'checked="checked" ' : '') . 'name="titre_on" type="checkbox" />Titre
						<input ' . ($parms['mots_cles_on'] ? 'checked="checked" ' : '') . 'name="mots_cles_on" type="checkbox" />Mots clés
					</td>
				</tr>');
} else if ($_SESSION['user']['privileges'] == 'superviseur') {
	echo('
			<table class="searchContainer">
				<tr>
					<th>Matière :</th>
					<td>
						<select name="id_matiere">
							<option value="-1">Toutes</option>');
	foreach ($parms['classes'] as $c) {
		echo('<optgroup label="' . $c['libelle'] . '">');
		foreach ($c['matieres'] as $m) {
			$cat = $c['id'] . ';' . $m['id'];
			echo('<option ' . (($c['id'] == $parms['id_classe']) && ($m['id'] == $parms['id_matiere']) ? 'selected="selected" ' : '') . 'value="' . $cat . '">' . $m['nom'] . '</option>');
		}
		echo('</optgroup>');
	}
	echo('
						</select>
					</td>
				</tr>');
}
echo('
			</table>
			<p class="submitContainer"><input name="validation" type="submit" value="Afficher" /></p>
		</form>
	</div>
	<p class="separator2"></p>');
?>
