<div class="selectionBox">
    <form action="" method="post">
<?php if ($_SESSION['user']['privileges'] == 'enseignant') : ?>
        <input name="id_enseignant" type="hidden" value="<?php echo $_SESSION['user']['id']; ?>" />
        <p class="headerSelectionBox">Veuillez saisir les informations relatives à votre réservation.</p>
<?php else : ?>
        <p class="headerSelectionBox">Veuillez saisir les informations relatives à la réservation.</p>
<?php endif; ?>
        <table class="searchContainer">
            <tr>
                <th>Date :</th>
                <td><input class="date" name="date_reservation" type="text" value="<?php echo @$_POST['date_reservation']; ?>" /></td>
            </tr>
            <tr>
                <th>De :</th>
                <td>
                    <select name="heure_debut_h">
<?php for ($h = 8; $h <= 19; $h++) : ?>
    <option <?php echo (@$_POST['heure_debut_h'] == $h ? 'selected="selected"' : ''); ?>value="<?php echo $h; ?>"><?php echo sprintf('%02d', $h); ?></option>
<?php endfor; ?>
                    </select> h 
                    <select name="heure_debut_m">
<?php $sm = isset($_POST['heure_debut_m']) ? $_POST['heure_debut_m'] : 30; ?>
<?php for ($m = 0; $m <= 30; $m = $m + 30) : ?>
    <option <?php echo ($m == $sm ? 'selected="selected"' : ''); ?>value="<?php echo $m; ?>"><?php echo sprintf('%02d', $m); ?></option>
<?php endfor; ?>
                    </select> <span class="thinSeparator">à</span> 
                    <select name="heure_fin_h">
<?php for ($h = 9; $h <= 20; $h++) : ?>
    <option <?php echo (@$_POST['heure_fin_h'] == $h ? 'selected="selected"' : ''); ?>value="<?php echo $h; ?>"><?php echo sprintf('%02d', $h); ?></option>
<?php endfor; ?>
                    </select> h 
                    <select name="heure_fin_m">
<?php $sm = isset($_POST['heure_fin_m']) ? $_POST['heure_fin_m'] : 30; ?>
<?php for ($m = 0; $m <= 30; $m = $m + 30) : ?>
    <option <?php echo ($m == $sm ? 'selected="selected"' : ''); ?>value="<?php echo $m; ?>"><?php echo sprintf('%02d', $m); ?></option>
<?php endfor; ?>
                    </select>
                </td>
            </tr>
            <?php if ($_SESSION['user']['privileges'] == 'superviseur') : ?>
            <tr>
                <th>Enseignant :</th>
                <td>
                    <select name="id_enseignant">
                        <option value=""></option>
                        <?php foreach ($parms['enseignants'] as $c) : ?>
                        <option <?php echo ($c['id'] == @$_POST['id_enseignant'] ? 'selected="selected" ' : ''); ?>value="<?php echo $c['id']; ?>"><?php echo $c['civility']; ?> <?php echo $c['nom']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
            </tr>
            <?php endif; ?>
            <tr>
                <th>Matériel :</th>
                <td>
                    <select name="id_materiel">
                    <?php $materiel_selected = isset($_POST['id_materiel']) ? $_POST['id_materiel'] : $parms['id_materiel']; ?>
                    <?php foreach ($parms['materiels'] as $m) : ?>
                        <option <?php echo ($m['id'] == $materiel_selected ? 'selected="selected" ' : ''); ?>value="<?php echo $m['id']; ?>"><?php echo $m['type']; ?> <?php echo $m['modele']; ?></option>
                    <?php endforeach; ?>
                    </select>
                </td>
            </tr>
        </table>
        <p class="submitContainer">
            <input name="validation" type="submit" value="Réserver" />
            <input name="annulation" type="submit" value="Annuler" />
        </p>
    </form>
</div>
