<div class="selectionBox">
    <form action="index.php?page=reservations&amp;action=delete&amp;id=<?php echo $parms['id']; ?>&amp;id_materiel=<?php echo $parms['id_materiel']; ?>" method="post">
        <p class="headerSelectionBox">Etes-vous sûr de vouloir supprimer cette réservation ?</p>
        <table class="searchContainer">
            <tr>
                <th>Date :</th>
                <td><?php echo $parms['date_reservation']; ?></td>
            </tr>
            <tr>
                <th>Heure de début :</th>
                <td><?php echo $parms['heure_debut']; ?></td>
            </tr>
            <tr>
                <th>Heure de fin :</th>
                <td><?php echo $parms['heure_fin']; ?></td>
            </tr>
            <?php if ($_SESSION['user']['privileges'] == 'superviseur') : ?>
            <tr>
                <th>Enseignant :</th>
                <td><?php echo $parms['enseignant']; ?></td>
            </tr>
            <?php endif; ?>
            <tr>
                <th>Matériel :</th>
                <td><?php echo $parms['materiel']; ?></td>
            </tr>
        </table>
        <p class="submitContainer">
            <input name="validation" type="submit" value="Supprimer" />
            <input name="annulation" type="submit" value="Annuler" />
        </p>
    </form>
</div>
