<div class="selectionBox">
    <form action="" method="post">
        <p class="headerSelectionBox">Etes-vous sûr de vouloir restaurer la sauvegarde du <b><?php echo $parms['date']; ?> à <?php echo $parms['heure']; ?></b> ?</p>
        <p class="submitContainer">
            <input name="validation" type="submit" value="Valider" />
            <input name="annulation" type="submit" value="Annuler" />
        </p>
    </form>
</div>
